language: python
python:
  - "3.8"
# command to install dependencies
services:
  -docker

before_script: pip install docker-compose

scripts:
  - docker-compose run app sh -c "python manage.py test && flake8"
